name: openapi_spec_plus
description: A Dart library for parsing and working with OpenAPI Specifications (v2.0, v3.0, and v3.1).
version: 0.5.0
repository: https://github.com/quick-start-dev/openapi_spec

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: ^1.17.0
  yaml: ^3.1.3
  yaml_writer: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^8.0.0
